### ISSUE TITLE
jQuery Mobile Bootstrap theme has been updated

### ISSUE THREAD

**Issue by commadelimited** [bauschan/generator-jquery-mobile#7]
A couple of things...

1) Thanks for using my Bootstrap theme project. I was just thinking about creating a generator for this the other day, but you've already done it. Good job.

2) I just updated both my [boilerplate project](https://github.com/commadelimited/jQuery-Mobile-Boilerplate) and my [Bootstrap project](https://github.com/commadelimited/jQuery-Mobile-Bootstrap-Theme) to use jQuery Mobile 1.4. You might consider updating yours.

3) To make it easier to update in the future, you also might consider using a [git submodule](http://git-scm.com/docs/git-submodule) instead of importing the files directly into your app.

4) Your project description has "genrator" spelled wrong. It should be "generator".

**Comment by bauschan** [comment]
Hi Andy,

Good points! I will add these to the next release.

Thanks for your feedback
~Peter
